//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTiemNet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Scheduler
    {
        [DisplayName("Scheduler")]
        public int Id { get; set; }
        public System.DateTime Time { get; set; }
        [DisplayName("User")]
        public int UserId { get; set; }
        [DisplayName("Computer")]
        public int ComputerId { get; set; }
        [DisplayName("Status")]
        public int StatusId { get; set; }
    
        public virtual Computer Computer { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
